from datetime import date
from platform import node
from site import execsitecustomize
import uuid
from venv import create

from numpy import var
from arches.app.models.models import Concept as modelConcept
from arches.app.models.concept import Concept
from arches.app.models.tile import Tile
from django.core.exceptions import ValidationError
from arches.app.functions.base import BaseFunction
import json

details = {
    "name": "Generate Node Value",
    "type": "node",
    "description": "Just a sample demonstrating node group selection",
    "defaultconfig": {"triggering_nodegroups": [],
                      "keys": { 
                            "Henryd":"Conwy",
                            "Pentwyn":"Cardiff",
                            "Llanarmon-yn-ial":"Denbighshire",
                            "Llanfihangel":"Powys",
                            "Brymbo":"Wrexham",
                            "Carmarthen":"Carmarthenshire",
                            "Llanyre":"Powys",
                            "Tremeirchion":"Denbighshire",
                            "Cynwyd":"Denbighshire",
                            "Victoria":"Newport",
                            "Nolton and Roch":"Pembrokeshire",
                            "Llanddoged and Maenan":"Conwy",
                            "Llanilar":"Ceredigion",
                            "Merthyr Mawr":"Bridgend",
                            "Solva":"Pembrokeshire",
                            "Penydarren":"Merthyr Tydfil",
                            "Aberaman":"Rhondda Cynon Taff",
                            "Cilmery":"Powys",
                            "Penyrheol":"Caerphilly",
                            "Llandyfaelog":"Carmarthenshire",
                            "Llanaelhaearn":"Gwynedd",
                            "Bro Machno":"Conwy",
                            "Cefn Cribwr":"Bridgend",
                            "St Fagans":"Cardiff",
                            "Cwmbach":"Rhondda Cynon Taff",
                            "Llanwrthwl":"Powys",
                            "Bodffordd":"Isle of Anglesey",
                            "Glasbury":"Powys",
                            "Caia Park":"Wrexham",
                            "Pencarreg":"Carmarthenshire",
                            "Llanfair (Gwynedd)":"Gwynedd",
                            "Efenechtyd":"Denbighshire",
                            "Y Ferwig":"Ceredigion",
                            "Goetre Fawr":"Monmouthshire",
                            "Pembroke Dock":"Pembrokeshire",
                            "Penmaen":"Caerphilly",
                            "Llanddulas and Rhyd-y-foel":"Conwy",
                            "Birchgrove":"Swansea",
                            "Offa":"Wrexham",
                            "Llangeitho":"Ceredigion",
                            "Ystrad Fflur":"Ceredigion",
                            "Cockett":"Swansea",
                            "Mynyddbach":"Swansea",
                            "New Moat":"Pembrokeshire",
                            "Pentrefoelas":"Conwy",
                            "Pant":"Merthyr Tydfil",
                            "St Davids and the Cathedral Close":"Pembrokeshire",
                            "Raglan":"Monmouthshire",
                            "Cwmllynfell":"Neath Port Talbot",
                            "Whitchurch":"Cardiff",
                            "Waunfawr":"Gwynedd",
                            "Tintern":"Monmouthshire",
                            "Penally":"Pembrokeshire",
                            "Glascwm":"Powys",
                            "Llandough":"The Vale of Glamorgan",
                            "St Nicholas and Bonvilston":"The Vale of Glamorgan",
                            "Rhosybol":"Isle of Anglesey",
                            "Usk":"Monmouthshire",
                            "Gresford":"Wrexham",
                            "Crumlin":"Caerphilly",
                            "Manordeifi":"Pembrokeshire",
                            "Ceiriog Ucha":"Wrexham",
                            "Castlemartin":"Pembrokeshire",
                            "Aberwheeler":"Denbighshire",
                            "Llanybydder":"Carmarthenshire",
                            "Park":"Merthyr Tydfil",
                            "Llannerch-y-medd":"Isle of Anglesey",
                            "Felin-fach":"Powys",
                            "Newport":"Pembrokeshire",
                            "Abergavenny":"Monmouthshire",
                            "Llangennith":"Swansea",
                            "Grangetown":"Cardiff",
                            "Llanfair Talhaiarn":"Conwy",
                            "Cynwyl Elfed":"Carmarthenshire",
                            "Trawsgoed":"Ceredigion",
                            "Llanrhidian Higher":"Swansea",
                            "Ambleston":"Pembrokeshire",
                            "Bryneglwys":"Denbighshire",
                            "New Inn":"Torfaen",
                            "Fairwater (Cardiff)":"Cardiff",
                            "Bro Garmon":"Conwy",
                            "Llangan":"The Vale of Glamorgan",
                            "Coedpoeth":"Wrexham",
                            "Sealand":"Flintshire",
                            "Cwmavon":"Neath Port Talbot",
                            "Llanllwchaiarn":"Ceredigion",
                            "Letterston":"Pembrokeshire",
                            "Upper Cwmbran":"Torfaen",
                            "RC_WALES_LKUP_WMAA_COMMUNITY_TEXT":"RC_WALES_LKUP_WMAA_COUNCIL_TEXT",
                            "Llandrillo":"Denbighshire",
                            "Barry":"The Vale of Glamorgan",
                            "Llanfarian":"Ceredigion",
                            "Llanarth (Monmouthshire)":"Monmouthshire",
                            "Ely":"Cardiff",
                            "Treorchy":"Rhondda Cynon Taff",
                            "Nevern":"Pembrokeshire",
                            "St Dogmaels":"Pembrokeshire",
                            "Castle Caereinion":"Powys",
                            "Llandysilio":"Powys",
                            "Coychurch Lower":"Bridgend",
                            "Pengam":"Caerphilly",
                            "Broughton and Bretton":"Flintshire",
                            "Blaengwrach":"Neath Port Talbot",
                            "Pillgwenlly":"Newport",
                            "Llangyndeyrn":"Carmarthenshire",
                            "St Julians":"Newport",
                            "Llangoed":"Isle of Anglesey",
                            "Sketty":"Swansea",
                            "Llanllwni":"Carmarthenshire",
                            "Llansadwrn":"Carmarthenshire",
                            "Llansilin":"Powys",
                            "Llansawel":"Carmarthenshire",
                            "Brithdir and Llanfachreth":"Gwynedd",
                            "Bontnewydd":"Gwynedd",
                            "Llanddewi Velfrey":"Pembrokeshire",
                            "Canton":"Cardiff",
                            "Hirwaun":"Rhondda Cynon Taff",
                            "Llanrwst":"Conwy",
                            "Pontardawe":"Neath Port Talbot",
                            "Slebech":"Pembrokeshire",
                            "Llanbradach":"Caerphilly",
                            "Llansteffan":"Carmarthenshire",
                            "St Arvans":"Monmouthshire",
                            "Splott":"Cardiff",
                            "Caersws":"Powys",
                            "Bangor Is-y-coed":"Wrexham",
                            "Old Colwyn":"Conwy",
                            "Penmynydd":"Isle of Anglesey",
                            "Llanidloes Without":"Powys",
                            "Abergele":"Conwy",
                            "Llanrhystyd":"Ceredigion",
                            "Caerphilly":"Caerphilly",
                            "Marloes and St Brides":"Pembrokeshire",
                            "St Asaph":"Denbighshire",
                            "Graig":"Newport",
                            "Ynysddu":"Caerphilly",
                            "Tenby":"Pembrokeshire",
                            "Llanelli Rural":"Carmarthenshire",
                            "Llanwrda":"Carmarthenshire",
                            "Llangurig":"Powys",
                            "Uplands":"Swansea",
                            "Glynneath":"Neath Port Talbot",
                            "Llanddeusant":"Carmarthenshire",
                            "Scleddau":"Pembrokeshire",
                            "Abertillery":"Blaenau Gwent",
                            "Llanfrynach":"Powys",
                            "St Thomas":"Swansea",
                            "Newbridge":"Caerphilly",
                            "New Quay":"Ceredigion",
                            "Llangybi (Ceredigion)":"Ceredigion",
                            "Llanedi":"Carmarthenshire",
                            "Painscastle":"Powys",
                            "Devauden":"Monmouthshire",
                            "Tylorstown":"Rhondda Cynon Taff",
                            "Llangamarch":"Powys",
                            "Ysceifiog":"Flintshire",
                            "Trearddur":"Isle of Anglesey",
                            "Briton Ferry":"Neath Port Talbot",
                            "Beguildy":"Powys",
                            "Penderry":"Swansea",
                            "Llan-maes":"The Vale of Glamorgan",
                            "Llanwern":"Newport",
                            "Llanfairfechan":"Conwy",
                            "Cilgerran":"Pembrokeshire",
                            "Brynford":"Flintshire",
                            "Rumney":"Cardiff",
                            "Langstone":"Newport",
                            "Llannor":"Gwynedd",
                            "Higher Kinnerton":"Flintshire",
                            "Llanddewi Ystradenny":"Powys",
                            "Stow Hill":"Newport",
                            "Llanfihangel Ystrad":"Ceredigion",
                            "Crucorney":"Monmouthshire",
                            "Meidrim":"Carmarthenshire",
                            "Ystrad":"Rhondda Cynon Taff",
                            "Llangynin":"Carmarthenshire",
                            "Halkyn":"Flintshire",
                            "Cefn Sidan":"Carmarthenshire",
                            "Chepstow":"Monmouthshire",
                            "Margam":"Neath Port Talbot",
                            "Hundleton":"Pembrokeshire",
                            "Llanelwedd":"Powys",
                            "Bodorgan":"Isle of Anglesey",
                            "Penycae":"Wrexham",
                            "Llanfihangel Cwmdu with Bwlch and Cathedine":"Powys",
                            "Ysbyty Ifan":"Conwy",
                            "Llanidan":"Isle of Anglesey",
                            "Newcastle Higher":"Bridgend",
                            "Llaneilian":"Isle of Anglesey",
                            "Glyncorrwg":"Neath Port Talbot",
                            "Maritime":"Maritime",
                            "Llandyrnog":"Denbighshire",
                            "Llanllyfni":"Gwynedd",
                            "Rogerstone":"Newport",
                            "Margam Moors":"Neath Port Talbot",
                            "Aberffraw":"Isle of Anglesey",
                            "Abbey Cwmhir":"Powys",
                            "Llanfihangel Rhydithon":"Powys",
                            "Llandaff North":"Cardiff",
                            "Pennard":"Swansea",
                            "Bronwydd":"Carmarthenshire",
                            "Llanbedr":"Gwynedd",
                            "Llanhilleth":"Blaenau Gwent",
                            "Bethesda":"Gwynedd",
                            "Mynachlog-ddu":"Pembrokeshire",
                            "Betws Gwerfil Goch":"Denbighshire",
                            "Nantmel":"Powys",
                            "Llanddeiniolen":"Gwynedd",
                            "Queensferry":"Flintshire",
                            "Buckley":"Flintshire",
                            "Denbigh":"Denbighshire",
                            "Wenvoe":"The Vale of Glamorgan",
                            "Caerau":"Cardiff",
                            "Ganllwyd":"Gwynedd",
                            "Llanwenog":"Ceredigion",
                            "Alway":"Newport",
                            "Clydau":"Pembrokeshire",
                            "Pen-y-waun":"Rhondda Cynon Taff",
                            "Carno":"Powys",
                            "Chirk":"Wrexham",
                            "Cwm Clydach":"Rhondda Cynon Taff",
                            "Mechell":"Isle of Anglesey",
                            "Portskewett":"Monmouthshire",
                            "Bishopston":"Swansea",
                            "Tref Alaw":"Isle of Anglesey",
                            "Llanbrynmair":"Powys",
                            "Meifod":"Powys",
                            "Flint":"Flintshire",
                            "Corwen":"Denbighshire",
                            "Llywel":"Powys",
                            "Panteg":"Torfaen",
                            "Bryn-crug":"Gwynedd",
                            "Barmouth":"Gwynedd",
                            "Angle":"Pembrokeshire",
                            "Trefnant":"Denbighshire",
                            "Criccieth":"Gwynedd",
                            "Glyntraian":"Wrexham",
                            "Welshpool":"Powys",
                            "Caernarfon":"Gwynedd",
                            "Llangors":"Powys",
                            "Killay":"Swansea",
                            "Llantwit Major":"The Vale of Glamorgan",
                            "Dyffryn Ardudwy":"Gwynedd",
                            "Rhosddu":"Wrexham",
                            "Cadfarch":"Powys",
                            "Tongwynlais":"Cardiff",
                            "Abenbury":"Wrexham",
                            "Llanelli":"Carmarthenshire",
                            "Talybont-on-usk":"Powys",
                            "Eglwyscummin":"Carmarthenshire",
                            "Maesteg":"Bridgend",
                            "Llanbister":"Powys",
                            "Blaenrheidol":"Ceredigion",
                            "Llangennech":"Carmarthenshire",
                            "Llanfair (The Vale of Glamorgan)":"The Vale of Glamorgan",
                            "Cilybebyll":"Neath Port Talbot",
                            "Camrose":"Pembrokeshire",
                            "Clynnog":"Gwynedd",
                            "Pistyll":"Gwynedd",
                            "Llanfihangel Aberbythych":"Carmarthenshire",
                            "Moelfre":"Isle of Anglesey",
                            "Pontardulais":"Swansea",
                            "Llanfaelog":"Isle of Anglesey",
                            "Troed-y-rhiw":"Merthyr Tydfil",
                            "Gwehelog Fawr":"Monmouthshire",
                            "Maenclochog":"Pembrokeshire",
                            "Dinas Cross":"Pembrokeshire",
                            "Llangwyryfon":"Ceredigion",
                            "Aberystwyth":"Ceredigion",
                            "Forden":"Powys",
                            "Llangyfelach":"Swansea",
                            "Ynysawdre":"Bridgend",
                            "Coedkernew":"Newport",
                            "Llandwrog":"Gwynedd",
                            "Cathays":"Cardiff",
                            "Wick":"The Vale of Glamorgan",
                            "Marshfield":"Newport",
                            "Cwmamman":"Carmarthenshire",
                            "Penrhyndeudraeth":"Gwynedd",
                            "Abercynon":"Rhondda Cynon Taff",
                            "Darran Valley":"Caerphilly",
                            "Grosmont":"Monmouthshire",
                            "Laleston":"Bridgend",
                            "Gwersyllt":"Wrexham",
                            "Vaynor":"Merthyr Tydfil",
                            "Cilcain":"Flintshire",
                            "Llanfihangel Ysgeifiog":"Isle of Anglesey",
                            "Ciliau Aeron":"Ceredigion",
                            "Aberhafesp":"Powys",
                            "Holywell":"Flintshire",
                            "Heath":"Cardiff",
                            "Talley":"Carmarthenshire",
                            "Llanfrothen":"Gwynedd",
                            "Llangynhafal":"Denbighshire",
                            "Tai Bach":"Neath Port Talbot",
                            "Narberth":"Pembrokeshire",
                            "Llansantffraid":"Powys",
                            "Menai Bridge":"Isle of Anglesey",
                            "Brackla":"Bridgend",
                            "Llanfechain":"Powys",
                            "Bausley with Criggion":"Powys",
                            "Llangelynin":"Gwynedd",
                            "New Radnor":"Powys",
                            "Nannerch":"Flintshire",
                            "Llawhaden":"Pembrokeshire",
                            "Llanbadrig":"Isle of Anglesey",
                            "Aberedw":"Powys",
                            "Llanfachraeth":"Isle of Anglesey",
                            "Llanddew":"Powys",
                            "Cyffylliog":"Denbighshire",
                            "Caldicot":"Monmouthshire",
                            "Gabalfa":"Cardiff",
                            "Gorslas":"Carmarthenshire",
                            "Rudry":"Caerphilly",
                            "Trevethin":"Torfaen",
                            "Llanboidy":"Carmarthenshire",
                            "Porthmadog":"Gwynedd",
                            "St Florence":"Pembrokeshire",
                            "Willington Worthenbury":"Wrexham",
                            "Bronllys":"Powys",
                            "Llanllechid":"Gwynedd",
                            "Llanfair-ar-y-bryn":"Carmarthenshire",
                            "Minera":"Wrexham",
                            "Y Felinheli":"Gwynedd",
                            "Abercarn":"Caerphilly",
                            "Guilsfield":"Powys",
                            "Llanharan":"Rhondda Cynon Taff",
                            "Llanwddyn":"Powys",
                            "Penbryn":"Ceredigion",
                            "Connahs Quay":"Flintshire",
                            "Llwchwr":"Swansea",
                            "Llangattock-vibon-avel":"Monmouthshire",
                            "Llangunllo":"Powys",
                            "Waen":"Denbighshire",
                            "Penyffordd":"Flintshire",
                            "Pont-y-clun":"Rhondda Cynon Taff",
                            "Glantwymyn":"Powys",
                            "The Vale of Grwyney":"Powys",
                            "Betws (Carmarthenshire)":"Carmarthenshire",
                            "Cray":"Powys",
                            "Llanwnda":"Gwynedd",
                            "Nash":"Newport",
                            "Llangattock":"Powys",
                            "Derwen":"Denbighshire",
                            "Blaenhonddan":"Neath Port Talbot",
                            "Leeswood":"Flintshire",
                            "Llanengan":"Gwynedd",
                            "Nelson":"Caerphilly",
                            "East Williamston":"Pembrokeshire",
                            "Ysgubor-y-coed":"Ceredigion",
                            "Llandissilio West":"Pembrokeshire",
                            "Rhayader":"Powys",
                            "Capel Curig":"Conwy",
                            "Ammanford":"Carmarthenshire",
                            "Penrhiwceiber":"Rhondda Cynon Taff",
                            "Coedffranc":"Neath Port Talbot",
                            "Dwyriw":"Powys",
                            "Dyffryn Clydach":"Neath Port Talbot",
                            "Beechwood":"Newport",
                            "Aberaeron":"Ceredigion",
                            "Rossett":"Wrexham",
                            "Llangynidr":"Powys",
                            "Puncheston":"Pembrokeshire",
                            "Gowerton":"Swansea",
                            "Dolbenmaen":"Gwynedd",
                            "The Havens":"Pembrokeshire",
                            "Pwllheli":"Gwynedd",
                            "Betws-y-coed":"Conwy",
                            "Pontyberem":"Carmarthenshire",
                            "Garw Valley":"Bridgend",
                            "Melindwr":"Ceredigion",
                            "Cenarth":"Carmarthenshire",
                            "Ysbyty Ystwyth":"Ceredigion",
                            "Baglan":"Neath Port Talbot",
                            "Cefn":"Wrexham",
                            "Kerry":"Powys",
                            "St Georges-super-ely":"The Vale of Glamorgan",
                            "Beulah":"Ceredigion",
                            "Pont-lliw":"Swansea",
                            "Cynwyl Gaeo":"Carmarthenshire",
                            "Eglwyswrw":"Pembrokeshire",
                            "Newcastle Emlyn":"Carmarthenshire",
                            "Llanbadarn Fynydd":"Powys",
                            "Riverside":"Cardiff",
                            "Llanrug":"Gwynedd",
                            "Montgomery":"Powys",
                            "Conwy":"Conwy",
                            "Northop Hall":"Flintshire",
                            "Hayscastle":"Pembrokeshire",
                            "Llanuwchllyn":"Gwynedd",
                            "St Ishmaels":"Pembrokeshire",
                            "Pentyrch":"Cardiff",
                            "Llandeilo":"Carmarthenshire",
                            "Trimsaran":"Carmarthenshire",
                            "Magor with Undy":"Monmouthshire",
                            "Tywyn":"Gwynedd",
                            "Dyffryn Cennen":"Carmarthenshire",
                            "Llangybi (Monmouthshire)":"Monmouthshire",
                            "Llanfair-mathafarn-eithaf":"Isle of Anglesey",
                            "Llangynog (Carmarthenshire)":"Carmarthenshire",
                            "Hay":"Powys",
                            "Welsh St Donats":"The Vale of Glamorgan",
                            "Treuddyn":"Flintshire",
                            "Pontllanfraith":"Caerphilly",
                            "Llantysilio":"Denbighshire",
                            "Gilfach Goch":"Rhondda Cynon Taff",
                            "Pentir":"Gwynedd",
                            "Tonyrefail":"Rhondda Cynon Taff",
                            "Llanwrtyd Wells":"Powys",
                            "Pelenna":"Neath Port Talbot",
                            "Townhill":"Swansea",
                            "Llanfaethlu":"Isle of Anglesey",
                            "Arthog":"Gwynedd",
                            "Cwm Cadnant":"Isle of Anglesey",
                            "Knighton":"Powys",
                            "Aber Valley":"Caerphilly",
                            "Talgarth":"Powys",
                            "Tawe-uchaf":"Powys",
                            "Llanfair Clydogau":"Ceredigion",
                            "Rhossili":"Swansea",
                            "Nantyglo and Blaina":"Blaenau Gwent",
                            "Croesyceiliog":"Torfaen",
                            "Wentlooge":"Newport",
                            "Trewern":"Powys",
                            "Freystrop":"Pembrokeshire",
                            "Brecon":"Powys",
                            "Llanidloes":"Powys",
                            "Mawr":"Swansea",
                            "Malpas":"Newport",
                            "Bargoed":"Caerphilly",
                            "Llangynfelyn":"Ceredigion",
                            "Henllan":"Denbighshire",
                            "Llanbadoc":"Monmouthshire",
                            "Marchwiel":"Wrexham",
                            "Tiers Cross":"Pembrokeshire",
                            "Llannon":"Carmarthenshire",
                            "Kinmel Bay and Towyn":"Conwy",
                            "Bodelwyddan":"Denbighshire",
                            "Eglwysbach":"Conwy",
                            "Gaer":"Newport",
                            "Shirenewton":"Monmouthshire",
                            "Llannefydd":"Conwy",
                            "Mostyn":"Flintshire",
                            "Rudbaxton":"Pembrokeshire",
                            "Llanelly":"Monmouthshire",
                            "Llanddewi Brefi":"Ceredigion",
                            "Llandygai":"Gwynedd",
                            "Llanberis":"Gwynedd",
                            "Mathry":"Pembrokeshire",
                            "Caerwent":"Monmouthshire",
                            "Neath":"Neath Port Talbot",
                            "Beaufort":"Blaenau Gwent",
                            "Ynysybwl and Coed-y-cwm":"Rhondda Cynon Taff",
                            "Ebbw Vale":"Blaenau Gwent",
                            "Radyr":"Cardiff",
                            "Geneur Glyn":"Ceredigion",
                            "Honddu Isaf":"Powys",
                            "Saundersfoot":"Pembrokeshire",
                            "Llanynys":"Denbighshire",
                            "Laugharne Township":"Carmarthenshire",
                            "Hanmer":"Wrexham",
                            "Llanharry":"Rhondda Cynon Taff",
                            "Pen-y-graig":"Rhondda Cynon Taff",
                            "Aberavon":"Neath Port Talbot",
                            "Fairwater (Torfaen)":"Torfaen",
                            "Caerleon":"Newport",
                            "Llangwm (Pembrokeshire)":"Pembrokeshire",
                            "Dyffryn Arth":"Ceredigion",
                            "Llancarfan":"The Vale of Glamorgan",
                            "Bonymaen":"Swansea",
                            "Cylch-y-garn":"Isle of Anglesey",
                            "Argoed":"Caerphilly",
                            "Nantglyn":"Denbighshire",
                            "Ynyshir":"Rhondda Cynon Taff",
                            "Myddfai":"Carmarthenshire",
                            "Llandyssil":"Powys",
                            "Llandrindod Wells":"Powys",
                            "Nefyn":"Gwynedd",
                            "St Mary Out Liberty":"Pembrokeshire",
                            "Dinas Powys":"The Vale of Glamorgan",
                            "Town":"Merthyr Tydfil",
                            "Rhoose":"The Vale of Glamorgan",
                            "Llanllawddog":"Carmarthenshire",
                            "Kidwelly":"Carmarthenshire",
                            "Talsarnau":"Gwynedd",
                            "Valley":"Isle of Anglesey",
                            "Presteigne":"Powys",
                            "Herbrandston":"Pembrokeshire",
                            "Troedyraur":"Ceredigion",
                            "Holt":"Wrexham",
                            "Llandudno":"Conwy",
                            "Monmouth":"Monmouthshire",
                            "Ruthin":"Denbighshire",
                            "Tredegar":"Blaenau Gwent",
                            "Johnston":"Pembrokeshire",
                            "Taffs Well":"Rhondda Cynon Taff",
                            "Cwm (Blaenau Gwent)":"Blaenau Gwent",
                            "Rhosyr":"Isle of Anglesey",
                            "Pencaer":"Pembrokeshire",
                            "Llysfaen":"Conwy",
                            "Llanafanfawr":"Powys",
                            "Blaenavon":"Torfaen",
                            "Llangwm (Conwy)":"Conwy",
                            "Pentraeth":"Isle of Anglesey",
                            "Trefriw":"Conwy",
                            "Llanover":"Monmouthshire",
                            "Peterston-super-ely":"The Vale of Glamorgan",
                            "Llanddarog":"Carmarthenshire",
                            "Caerhun":"Conwy",
                            "Mawddwy":"Gwynedd",
                            "Beaumaris":"Isle of Anglesey",
                            "Llandrinio":"Powys",
                            "Grovesend":"Swansea",
                            "Dowlais":"Merthyr Tydfil",
                            "Rhigos":"Rhondda Cynon Taff",
                            "Shaftesbury":"Newport",
                            "Nercwys":"Flintshire",
                            "Acton":"Wrexham",
                            "Llantarnam":"Torfaen",
                            "Rhos-on-sea":"Conwy",
                            "Broughton":"Wrexham",
                            "Llangoedmor":"Ceredigion",
                            "Trelech":"Carmarthenshire",
                            "Corris":"Gwynedd",
                            "Llanddowror":"Carmarthenshire",
                            "Aberporth":"Ceredigion",
                            "Tonypandy":"Rhondda Cynon Taff",
                            "Maentwrog":"Gwynedd",
                            "Llanddona":"Isle of Anglesey",
                            "Llandybie":"Carmarthenshire",
                            "Trehafod":"Rhondda Cynon Taff",
                            "Ystalyfera":"Neath Port Talbot",
                            "Upper Killay":"Swansea",
                            "Tregynon":"Powys",
                            "Dyserth":"Denbighshire",
                            "Mitchel Troy":"Monmouthshire",
                            "Shotton":"Flintshire",
                            "Seven Sisters":"Neath Port Talbot",
                            "Llanfynydd (Flintshire)":"Flintshire",
                            "Rhosllanerchrugog":"Wrexham",
                            "Mochdre (Powys)":"Powys",
                            "Llanarth (Ceredigion)":"Ceredigion",
                            "Ferndale":"Rhondda Cynon Taff",
                            "Brynmawr":"Blaenau Gwent",
                            "Llandysul":"Ceredigion",
                            "Trelawnyd and Gwaenysgor":"Flintshire",
                            "St Athan":"The Vale of Glamorgan",
                            "Cynffig":"Bridgend",
                            "Carew":"Pembrokeshire",
                            "New Tredegar":"Caerphilly",
                            "Pendine":"Carmarthenshire",
                            "Baglan Bay":"Neath Port Talbot",
                            "Beddgelert":"Gwynedd",
                            "Butetown":"Cardiff",
                            "Llanfair Pwllgwyngyll":"Isle of Anglesey",
                            "Gladestry":"Powys",
                            "Cardigan":"Ceredigion",
                            "Morriston":"Swansea",
                            "Cwm (Denbighshire)":"Denbighshire",
                            "Cefn Fforest":"Caerphilly",
                            "Rosemarket":"Pembrokeshire",
                            "Glyn Tarell":"Powys",
                            "Duhonw":"Powys",
                            "Porthcawl":"Bridgend",
                            "Tredegar Park":"Newport",
                            "Borth":"Ceredigion",
                            "Merthyr Vale":"Merthyr Tydfil",
                            "Lamphey":"Pembrokeshire",
                            "Dolwyddelan":"Conwy",
                            "Llanfihangel Glyn Myfyr":"Conwy",
                            "Lledrod":"Ceredigion",
                            "Trealaw":"Rhondda Cynon Taff",
                            "Cowbridge with Llanblethian":"The Vale of Glamorgan",
                            "Pembroke":"Pembrokeshire",
                            "Llansantffraed":"Ceredigion",
                            "Saltney":"Flintshire",
                            "Mountain Ash":"Rhondda Cynon Taff",
                            "Llanegryn":"Gwynedd",
                            "Mold":"Flintshire",
                            "Llansannan":"Conwy",
                            "Llanpumsaint":"Carmarthenshire",
                            "Llansamlet":"Swansea",
                            "St Donats":"The Vale of Glamorgan",
                            "Trewalchmai":"Isle of Anglesey",
                            "Manorbier":"Pembrokeshire",
                            "Coychurch Higher":"Bridgend",
                            "Llandovery":"Carmarthenshire",
                            "Machynlleth":"Powys",
                            "Betws Garmon":"Gwynedd",
                            "Bryngwran":"Isle of Anglesey",
                            "Penllergaer":"Swansea",
                            "Ceulanamaesmawr":"Ceredigion",
                            "Milford Haven":"Pembrokeshire",
                            "Martletwy":"Pembrokeshire",
                            "Llanbadarn Fawr (Ceredigion)":"Ceredigion",
                            "Mumbles":"Swansea",
                            "Kilgetty-begelly":"Pembrokeshire",
                            "Dale":"Pembrokeshire",
                            "St Harmon":"Powys",
                            "Llanasa":"Flintshire",
                            "Llangynwyd Lower":"Bridgend",
                            "Rhoscolyn":"Isle of Anglesey",
                            "Llandaff":"Cardiff",
                            "Boncath":"Pembrokeshire",
                            "Llangynwyd Middle":"Bridgend",
                            "Llandegla":"Denbighshire",
                            "Ystradgynlais":"Powys",
                            "Tirymynach":"Ceredigion",
                            "Bala":"Gwynedd",
                            "Faenor":"Ceredigion",
                            "Llangadog":"Carmarthenshire",
                            "Pontprennau":"Cardiff",
                            "Llandow":"The Vale of Glamorgan",
                            "Sandfields West":"Neath Port Talbot",
                            "Tregaron":"Ceredigion",
                            "Mynydd Isa":"Flintshire",
                            "Hawarden":"Flintshire",
                            "Cefnmeiriadog":"Denbighshire",
                            "Manafon":"Powys",
                            "Yscir":"Powys",
                            "Whitton":"Powys",
                            "Banwy":"Powys",
                            "Cosheston":"Pembrokeshire",
                            "Llangefni":"Isle of Anglesey",
                            "Sesswick":"Wrexham",
                            "Llantrisant":"Rhondda Cynon Taff",
                            "Lampeter Velfrey":"Pembrokeshire",
                            "Walwyns Castle":"Pembrokeshire",
                            "Llangwm (Monmouthshire)":"Monmouthshire",
                            "Llanegwad":"Carmarthenshire",
                            "Llanystumdwy":"Gwynedd",
                            "Plasnewydd":"Cardiff",
                            "Trefeurig":"Ceredigion",
                            "Llanfihangel Rhos-y-corn":"Carmarthenshire",
                            "Llanfair Dyffryn Clwyd":"Denbighshire",
                            "Llanwnnen":"Ceredigion",
                            "Port Talbot":"Neath Port Talbot",
                            "Llwyn-y-pia":"Rhondda Cynon Taff",
                            "Llangollen Rural":"Wrexham",
                            "Neyland":"Pembrokeshire",
                            "Cwmbwrla":"Swansea",
                            "Cwmbran Central":"Torfaen",
                            "Llantilio Pertholey":"Monmouthshire",
                            "Buan":"Gwynedd",
                            "Llansantffraid Glyn Ceiriog":"Wrexham",
                            "Llandderfel":"Gwynedd",
                            "Gwernaffield":"Flintshire",
                            "Jeffreyston":"Pembrokeshire",
                            "Colwinston":"The Vale of Glamorgan",
                            "Pontymoile":"Torfaen",
                            "Northop":"Flintshire",
                            "Gelligaer":"Caerphilly",
                            "Bryn":"Neath Port Talbot",
                            "Castle (Swansea)":"Swansea",
                            "Maelor South":"Wrexham",
                            "Llanferres":"Denbighshire",
                            "Dolgellau":"Gwynedd",
                            "Llanrhidian Lower":"Swansea",
                            "Penmaenmawr":"Conwy",
                            "Llanhennock":"Monmouthshire",
                            "Prestatyn":"Denbighshire",
                            "Landore":"Swansea",
                            "Bagillt":"Flintshire",
                            "Sully":"The Vale of Glamorgan",
                            "Mochdre (Conwy)":"Conwy",
                            "Colwyn Bay":"Conwy",
                            "St Ishmael":"Carmarthenshire",
                            "Isycoed":"Wrexham",
                            "Crymych":"Pembrokeshire",
                            "Erbistock":"Wrexham",
                            "Ystradfellte":"Powys",
                            "Llanerfyl":"Powys",
                            "Ruabon":"Wrexham",
                            "Bedwas":"Caerphilly",
                            "Llanrhaeadr-yng-nghinmeirch":"Denbighshire",
                            "Old St Mellons":"Cardiff",
                            "Penllyn":"The Vale of Glamorgan",
                            "Llanfihangel-y-pennant":"Gwynedd",
                            "Llangynog (Powys)":"Powys",
                            "Trallong":"Powys",
                            "Bodfari":"Denbighshire",
                            "Trecwn":"Pembrokeshire",
                            "Crickhowell":"Powys",
                            "Pennal":"Gwynedd",
                            "Redwick":"Newport",
                            "Trawsfynydd":"Gwynedd",
                            "St Clears":"Carmarthenshire",
                            "Manordeilo and Salem":"Carmarthenshire",
                            "Gwernyfed":"Powys",
                            "Pendoylan":"The Vale of Glamorgan",
                            "Ewenny":"The Vale of Glamorgan",
                            "Goldcliff":"Newport",
                            "Llangain":"Carmarthenshire",
                            "Nantcwnlle":"Ceredigion",
                            "Pontypridd":"Rhondda Cynon Taff",
                            "Trellech United":"Monmouthshire",
                            "Pontnewydd":"Torfaen",
                            "Llandyfriog":"Ceredigion",
                            "Maerdy":"Rhondda Cynon Taff",
                            "Llangyniew":"Powys",
                            "Allt-yr-yn":"Newport",
                            "Llangollen":"Denbighshire",
                            "Bridgend":"Bridgend",
                            "Dolgarrog":"Conwy",
                            "Michaelston":"The Vale of Glamorgan",
                            "Templeton":"Pembrokeshire",
                            "Quarter Bach":"Carmarthenshire",
                            "Treharris":"Merthyr Tydfil",
                            "Llangunnor":"Carmarthenshire",
                            "Wolfscastle":"Pembrokeshire",
                            "Cymmer":"Rhondda Cynon Taff",
                            "Sandfields East":"Neath Port Talbot",
                            "Resolven":"Neath Port Talbot",
                            "Pencoed":"Bridgend",
                            "Llanwinio":"Carmarthenshire",
                            "Gwernymynydd":"Flintshire",
                            "Hope":"Flintshire",
                            "Llanddyfnan":"Isle of Anglesey",
                            "Llanigon":"Powys",
                            "Lisvane":"Cardiff",
                            "Llanrhaeadr-ym-mochnant":"Powys",
                            "Clocaenog":"Denbighshire",
                            "Amlwch":"Isle of Anglesey",
                            "Cyfarthfa":"Merthyr Tydfil",
                            "Disserth and Trecoed":"Powys",
                            "Llantrisant Fawr":"Monmouthshire",
                            "Llanycrwys":"Carmarthenshire",
                            "Bishton":"Newport",
                            "Rhiwbina":"Cardiff",
                            "Roath":"Cardiff",
                            "Berriew":"Powys",
                            "Llanfihangel-ar-arth":"Carmarthenshire",
                            "Bodedern":"Isle of Anglesey",
                            "Wiston":"Pembrokeshire",
                            "Overton":"Wrexham",
                            "Stackpole":"Pembrokeshire",
                            "Onllwyn":"Neath Port Talbot",
                            "Aberdaron":"Gwynedd",
                            "Pen Tranch":"Torfaen",
                            "Penhow":"Newport",
                            "Llangedwyn":"Powys",
                            "Port Eynon":"Swansea",
                            "Trowbridge":"Cardiff",
                            "Clyro":"Powys",
                            "Mathern":"Monmouthshire",
                            "Treherbert":"Rhondda Cynon Taff",
                            "Porth":"Rhondda Cynon Taff",
                            "Rhyl":"Denbighshire",
                            "Castle (Cardiff)":"Cardiff",
                            "Henllys":"Torfaen",
                            "Ringland":"Newport",
                            "Merthyr Cynog":"Powys",
                            "Coity Higher":"Bridgend",
                            "Blackwood":"Caerphilly",
                            "St Brides Minor (Bridgend)":"Bridgend",
                            "Llanfoist Fawr":"Monmouthshire",
                            "Gwyddelwern":"Denbighshire",
                            "Maesycwmmer":"Caerphilly",
                            "Llanbedrog":"Gwynedd",
                            "Erwood":"Powys",
                            "Botwnnog":"Gwynedd",
                            "Llanfyllin":"Powys",
                            "Penrice":"Swansea",
                            "Llangernyw":"Conwy",
                            "Van":"Caerphilly",
                            "Henllanfallteg":"Carmarthenshire",
                            "Uzmaston and Boulston":"Pembrokeshire",
                            "Llwydcoed":"Rhondda Cynon Taff",
                            "Harlech":"Gwynedd",
                            "Abersychan":"Torfaen",
                            "Ogmore Valley":"Bridgend",
                            "Llanvaches":"Newport",
                            "Abernant":"Carmarthenshire",
                            "Treflys":"Powys",
                            "Abergwili":"Carmarthenshire",
                            "Whitford":"Flintshire",
                            "Henfynyw":"Ceredigion",
                            "Llay":"Wrexham",
                            "St Brides Major (The Vale of Glamorgan)":"The Vale of Glamorgan",
                            "Llanyrafon":"Torfaen",
                            "Crosskeys":"Caerphilly",
                            "Bedlinog":"Merthyr Tydfil",
                            "Cyncoed":"Cardiff",
                            "Haverfordwest":"Pembrokeshire",
                            "Llantilio Crossenny":"Monmouthshire",
                            "Llanycil":"Gwynedd",
                            "Gwaun-cae-gurwen":"Neath Port Talbot",
                            "Bettws (Newport)":"Newport",
                            "Llangathen":"Carmarthenshire",
                            "Newtown and Llanllwchaiarn":"Powys",
                            "Lampeter":"Ceredigion",
                            "Brawdy":"Pembrokeshire",
                            "Cerrigydrudion":"Conwy",
                            "Spittal":"Pembrokeshire",
                            "Risca":"Caerphilly",
                            "Clydach":"Swansea",
                            "Penybont":"Powys",
                            "Bangor":"Gwynedd",
                            "Bettws (Powys)":"Powys",
                            "Ilston":"Swansea",
                            "Llandinam":"Powys",
                            "Llandysiliogogo":"Ceredigion",
                            "Llanstadwell":"Pembrokeshire",
                            "Llangristiolus":"Isle of Anglesey",
                            "Caerwys":"Flintshire",
                            "Betws yn Rhos":"Conwy",
                            "Reynoldston":"Swansea",
                            "Burton":"Pembrokeshire",
                            "Churchstoke":"Powys",
                            "Llanbadarn Fawr (Powys)":"Powys",
                            "Ystrad Meurig":"Ceredigion",
                            "Gurnos":"Merthyr Tydfil",
                            "Aber":"Gwynedd",
                            "Whitland":"Carmarthenshire",
                            "Builth":"Powys",
                            "Llanfynydd (Carmarthenshire)":"Carmarthenshire",
                            "Merlins Bridge":"Pembrokeshire",
                            "Clyne and Melincourt":"Neath Port Talbot",
                            "Llanddaniel Fab":"Isle of Anglesey",
                            "Clynderwen":"Carmarthenshire",
                            "Maescar":"Powys",
                            "Llaneugrad":"Isle of Anglesey",
                            "Rhymney":"Caerphilly",
                            "Rhuddlan":"Denbighshire",
                            "Llanfair Caereinion":"Powys",
                            "Carreghofa":"Powys",
                            "Rogiet":"Monmouthshire",
                            "Newchurch and Merthyr":"Carmarthenshire",
                            "Llangrannog":"Ceredigion",
                            "Llangeler":"Carmarthenshire",
                            "Holyhead":"Isle of Anglesey",
                            "Michaelstone-y-fedw":"Newport",
                            "Llangywer":"Gwynedd",
                            "Llanfair-yn-neubwll":"Isle of Anglesey",
                            "Llanelltyd":"Gwynedd",
                            "Pontarfynach":"Ceredigion",
                            "Pentre":"Rhondda Cynon Taff",
                            "Llanrumney":"Cardiff",
                            "Aberdovey":"Gwynedd",
                            "Aberdare":"Rhondda Cynon Taff",
                            "Trefeglwys":"Powys",
                            "Amroth":"Pembrokeshire",
                            "Llanrhian":"Pembrokeshire",
                            "Fishguard and Goodwick":"Pembrokeshire",
                            "Llantwit Fardre":"Rhondda Cynon Taff",
                            "Cilymaenllwyd":"Carmarthenshire",
                            "Llanarthney":"Carmarthenshire",
                            "Dunvant":"Swansea",
                            "Bronington":"Wrexham",
                            "Llanishen":"Cardiff",
                            "Llanbedr Dyffryn Clwyd":"Denbighshire",
                            "Ponthir":"Torfaen",
                            "Gorseinon":"Swansea",
                            "Liswerry":"Newport",
                            "Tudweiliog":"Gwynedd",
                            "Old Radnor":"Powys",
                            "Llansanffraid Glan Conwy":"Conwy",
                            "Ffestiniog":"Gwynedd",
                            "Esclusham":"Wrexham",
                            "Pen-y-bont-fawr":"Powys",
                            "Penarth":"The Vale of Glamorgan",
                            "Cilycwm":"Carmarthenshire",
                            "Llanelidan":"Denbighshire",
                            "Crynant":"Neath Port Talbot",
                            "Adamsdown":"Cardiff",
                            "Tonna":"Neath Port Talbot",
                            "Cwm Gwaun":"Pembrokeshire",


                        }
                      },
    "classname": "UnitaryFunction",
    "component": "views/components/functions/generate_node_value",
}

#Methods
def createNewTile(keys, source_tile):
    '''
    Description:
    Creates a new Unitary Authority tile 
    
    Parameters:
    :source_tile: Triggering tile
    
    Returns:
    :target_tile: Returns a new tile with all required data
    '''
    
    #Nodes
    unitary_authority = '60120f64-9ff2-11ea-a530-000d3a86d704' #Unitary Authority nodegroup uuid
    ua_value = "60120f46-9ff2-11ea-a530-000d3a86d704" #Unitary Authority's node uuid
    
    #UUID's for the right side of the default.config.keys dictionary 
    rhs_key = source_tile.data[list(source_tile.data.keys())[0]] #Always fetch the first element as only one value can be selected
    
    #Request new blank tile of resource instance from unitary authority
    target_tile = Tile().get_blank_tile_from_nodegroup_id(unitary_authority, source_tile.resourceinstance_id)
    target_tile.parenttile_id = source_tile.parenttile_id
    
    #Add UA data to new tile
    target_tile.data[ua_value] = keys[rhs_key]

    return target_tile

def getConcepts(self):
    '''
    Description:
    This functions takes a word dictionary and convert it to UUID dictionary
    
    Parameters:
    'source_thesauri_id': Left hand thesauri  of the default config keys
    'target_thesauri_id': Right hand thesauri of th default config keys
    
    Returns:
    'new_keys': Returns the original dictionary with words converted to UUID's
    '''
    #source_thesauri_id
    source_thesauri_id = "727c6595-1487-41b1-8e37-ad416e0d9345" # to be changed  community value thesauri uuid
    target_thesauri_id = "ab62df43-c1e3-40bb-956a-8e7770497cbd" # to be changed unitary authority thesauri uuid
    
    new_keys = {}

    #Left hand side of default config keys
    source_thesauri = Concept().get(
        id=source_thesauri_id,
        include_subconcepts=True,
        include_parentconcepts=False,
        include_relatedconcepts=True,
        depth_limit=None,
        up_depth_limit=None,
    )

    #Right hand side of default config keys
    target_thesauri = Concept().get(
        id=target_thesauri_id,
        include_subconcepts=True,
        include_parentconcepts=False,
        include_relatedconcepts=True,
        depth_limit=None,
        up_depth_limit=None,
    )
    

    for source_subc in source_thesauri.subconcepts: # for each concept in left hand thesauri
        for target_subc in target_thesauri.subconcepts:# for each concept in right hand thesauri 
            if target_subc.values[0].value == self.config['keys'][source_subc.values[0].value]: # check whether left hand concept(text) matches default config keys
                new_keys[source_subc.values[0].id] = target_subc.values[0].id # If match create a new key with lef hand concept UUID and right hand concept UUID
                
    return new_keys

#TODO: Stop it form triggering twice 

class UnitaryFunction(BaseFunction):

    def save(self, tile, request):
        #Get concept UUIDs from word values
        self.config['keys'] = getConcepts(self)
        
        #Variables
        source_tile = tile
        print(f'srouce tile: {vars(source_tile)}')
        exists = False

        #Create target tile 
        target_tile = createNewTile(self.config['keys'], source_tile)
        
        #Check if source_tile has one or more target tiles 
        if Tile.objects.filter(resourceinstance_id = source_tile.resourceinstance_id, nodegroup_id = target_tile.nodegroup_id).exists():
            #if true called all instances of target tile 
            target_tiles = Tile.objects.filter(resourceinstance_id = source_tile.resourceinstance_id, nodegroup_id = target_tile.nodegroup)
            
            #For each tile check if Unitary Authority tile already exists
            for tile in target_tiles:
                if str(tile.nodegroup_id) == '60120f64-9ff2-11ea-a530-000d3a86d704': #Unitary Authority 
                    #If so remove it and add the new one, since there can only be one
                    tile.delete()
                    target_tile.save()
                    return

        #If no target tiles exist just save a new tile   
        if not exists:
            target_tile.save()
            
        return
                
